# Generated by Django 4.1.5 on 2023-01-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
