# Generated by Django 4.1.5 on 2023-02-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_patient_user_is_staff_user_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
